# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]
      - id: check-added-large-files
      - id: check-json
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys]
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.7.0-1
    hooks:
      - id: shfmt
        args: [-w, -s, -bn, -i=2]
        # Reset types to all text files so we can format dockerfiles as well
        types: [text]
        types_or: [shell, dockerfile]
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
    - id: mdformat
      args: [--wrap=80]
      # Optionally add plugins
      additional_dependencies:
      - mdformat-gfm
      - mdformat-tables
exclude: |
  (?x)^(
    .*\.patch$|
    .*\.test\.(j|t)sx?\.snap$
  )$
